### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by cesarkohl** [voycey/cakephp-newrelic#1]
Hi Voycey, how are you?

My CakePHP version is 3.2.11, I installed it via Composer but, unfortunately, my New Relic transactions only show one URL "/webroot/index.php".

How can I make it work?

Thanks in advance.

Best,
Cesar

**Comment by dmromanov** [comment]
Same here

**Comment by voycey** [comment]
Have you installed the middleware stack into your application? I havent
looked at this for a while but its in one of my apps and its working - ill
take a look next week!

You should probably both upgrade your Cake version too!

**Comment by dmromanov** [comment]
@voycey Right. The middleware subsystem was misssing in our application. I've enabled it by the instruction https://book.cakephp.org/3.0/en/controllers/middleware.html#adding-the-new-http-stack-to-an-existing-application and the plugin started to work.
Thank you.
